# Generated by Django 4.0.2 on 2022-03-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=50)),
                ('owner_email', models.EmailField(max_length=50)),
                ('owner_contact', models.IntegerField()),
                ('owner_address', models.TextField()),
            ],
            options={
                'db_table': 'owner',
            },
        ),
    ]
