# Generated by Django 4.0.2 on 2022-03-23 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField(null=True)),
                ('data_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50)),
                ('role_description', models.TextField()),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('role_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orm.role')),
                ('employee_name', models.CharField(max_length=50)),
                ('employee_email', models.CharField(max_length=50)),
                ('employee_password', models.CharField(max_length=50)),
                ('employee_phone', models.CharField(max_length=50)),
                ('employee_address', models.TextField()),
                ('employee_dob', models.DateField()),
            ],
            options={
                'db_table': 'employee',
            },
            bases=('orm.role',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('student_email', models.CharField(max_length=50)),
                ('student_password', models.CharField(max_length=50)),
                ('student_phone', models.CharField(max_length=50)),
                ('student_address', models.TextField()),
                ('student_dob', models.DateField()),
                ('role_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orm.role')),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('STATUS', models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('completed', 'completed')], max_length=200)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orm.customer')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orm.product')),
            ],
            options={
                'db_table': 'order_details',
            },
        ),
    ]
