# Generated by Django 4.0.2 on 2022-02-16 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0004_product_data_created_product_name_product_price_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
