# Generated by Django 4.0.2 on 2022-02-28 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0006_remove_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
    ]
