# Generated by Django 4.0.2 on 2022-02-28 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0010_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
