# Generated by Django 4.0.2 on 2022-02-28 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0012_order_product_alter_order_customer'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='order_details',
        ),
    ]
