# Generated by Django 4.0.2 on 2022-02-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50)),
                ('service_price', models.IntegerField()),
                ('service_discription', models.TextField()),
                ('service_quantity', models.IntegerField()),
            ],
        ),
    ]
