# Generated by Django 4.0.2 on 2022-02-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_servicecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_vehicle_num',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
