# Generated by Django 4.0.2 on 2022-03-13 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_remove_user_role_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role_id',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='userapp.role'),
            preserve_default=False,
        ),
    ]
